# -*- coding: utf-8 -*-
"""DATA PREPROCESSING (SPRINT 1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13RKxZLxXg9OHXYsd2Le_OI2D8nbWSIMK
"""

import pandas as pd
import numpy as np

#1. LOAD DATA
url = "https://raw.githubusercontent.com/cathya666/WGTIK-Kelompok_9/refs/heads/main/DATASETS/clean_stunting_dataset.csv"
df = pd.read_csv(url)

print("dataset berhasil dimuat")
print("shape:", df.shape)
print("\nkolom:", df.columns.tolist())
df.head()

#2. DATA SEBELUM PREPROCESSING
print("info data:")
df.info()

print("\nmissing value per kolom:")
print(df.isnull().sum())

print("\nstatistik deskriptif:")
df.describe()

#3. CLEANING DATA
#missing value
#kolom BMI dan Head_Circumference seluruhnya kosong (100% NaN)
#tidak bisa diisi karena tidak ada data sama sekali, jadi drop
print("kolom dengan semua nilai kosong:")
print(df.columns[df.isnull().all()].tolist())
df = df.drop(columns=['BMI', 'Head_Circumference'])
print("kolom setelah drop:", df.columns.tolist())

#kolom Weight dan MUAC sebagian besar kosong (39.425 dari 44.425 baris)
#isi pakai median supaya tidak membuang terlalu banyak data
df['Weight'] = df['Weight'].fillna(df['Weight'].median())
df['MUAC']   = df['MUAC'].fillna(df['MUAC'].median())

#kolom Gender sebagian kosong, isi dengan 'unknown'
df['Gender'] = df['Gender'].fillna('unknown')
print("\nmissing value setelah ditangani:")
print(df.isnull().sum())

#duplikasi
print("\njumlah duplikasi:", df.duplicated().sum())
df = df.drop_duplicates()
print("jumlah duplikasi setelah dihapus:", df.duplicated().sum())

#4. FORMATTING
#rename kolom
df = df.rename(columns={
    'Age'              : 'Age_Months',
    'Height'           : 'Height_cm',
    'Weight'           : 'Weight_kg',
    'MUAC'             : 'MUAC_cm',
    'Gender'           : 'Gender',
    'Nutrition_Status' : 'Nutrition_Status',
    'Stunting'         : 'Stunting'
})
print("kolom setelah rename:", df.columns.tolist())

#konversi tipe data
df['Age_Months']      = df['Age_Months'].round(0).astype(int)
df['Gender']          = df['Gender'].astype('category')
df['Nutrition_Status']= df['Nutrition_Status'].astype('category')

print("\ntipe data setelah konversi:")
print(df.dtypes)

#5. FILTERING & TRANSFORMASI
#filter usia 0-60 bulan (definisi balita)
sebelum = len(df)
df = df[df['Age_Months'] <= 60].reset_index(drop=True)
print(f"baris dihapus karena usia > 60 bulan: {sebelum - len(df)}")
print("shape setelah filter:", df.shape)

#standarisasi label Nutrition_Status ke title case
df['Nutrition_Status'] = df['Nutrition_Status'].str.title().astype('category')
print("\nnilai unik Nutrition_Status:", df['Nutrition_Status'].cat.categories.tolist())

#DATA SETELAH PREPROCESSING
print("\nshape akhir:", df.shape)
print("\n10 baris pertama setelah preprocessing:")
df.head(10)