# -*- coding: utf-8 -*-
"""ChatBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15xaO2BBdEued1ZdaZtVVq9c3alLjQpYN
"""

#Install library
!pip install fastapi uvicorn nest-asyncio --quiet
print('Semua library berhasil diinstall!')

#chatbot/engine.py
#Chatbot Engine + NLP
#NutriScan: Sistem Deteksi & Edukasi Stunting

import re
from typing import Dict, List, Optional, Tuple
from datetime import datetime

#CONTEXT HANDLER - Menyimpan history chat
class ChatContext:
    """
    Menyimpan history percakapan agar chatbot lebih natural.
    Max history = 5 pertukaran pesan terakhir.
    """

    def __init__(self, max_history: int = 5):
        self.history: List[Dict] = []
        self.last_intent: Optional[str] = None
        self.max_history = max_history

    def add_message(self, role: str, message: str, intent: Optional[str] = None):
        self.history.append({
            "role": role,
            "message": message,
            "intent": intent,
            "timestamp": datetime.now().strftime("%H:%M:%S")
        })
        if len(self.history) > self.max_history * 2:
            self.history = self.history[-(self.max_history * 2):]
        if intent:
            self.last_intent = intent

    def reset(self):
        self.history = []
        self.last_intent = None

    def get_history(self) -> List[Dict]:
        return self.history

#SIMPLE NLP - Tokenisasi & Normalisasi Teks
class SimpleNLP:
    """
    NLP sederhana berbasis regex untuk Bahasa Indonesia.
    Normalisasi kata gaul + tokenisasi unigram/bigram/trigram.
    Tidak membutuhkan library NLTK eksternal.
    """

    SLANG_MAP = {
        "gak": "tidak", "ga": "tidak", "ngga": "tidak", "nggak": "tidak",
        "udah": "sudah", "udh": "sudah",
        "gimana": "bagaimana", "gmn": "bagaimana",
        "kenapa": "mengapa", "knp": "mengapa",
        "org": "orang", "yg": "yang", "dgn": "dengan",
        "utk": "untuk", "krn": "karena", "karna": "karena",
        "spt": "seperti", "tp": "tapi", "tpi": "tapi",
        "sy": "saya", "aku": "saya",
        "nutrisi": "gizi", "mkn": "makanan",
        "hrs": "harus",
    }

    @staticmethod
    def normalize(text: str) -> str:
        text = text.lower().strip()
        text = re.sub(r"[^\w\s]", " ", text)
        text = re.sub(r"\s+", " ", text)
        words = text.split()
        words = [SimpleNLP.SLANG_MAP.get(w, w) for w in words]
        return " ".join(words)

    @staticmethod
    def tokenize(text: str) -> List[str]:
        return re.findall(r"\b\w+\b", SimpleNLP.normalize(text))

    @staticmethod
    def get_all_phrases(text: str) -> List[str]:
        """Buat unigram, bigram, trigram, 4-gram untuk keyword matching akurat."""
        tokens = SimpleNLP.tokenize(text)
        phrases = list(tokens)
        for n in range(2, 5):
            for i in range(len(tokens) - n + 1):
                phrases.append(" ".join(tokens[i:i+n]))
        return phrases

#INTENT CLASSIFIER - Klasifikasi Intent Berbasis Bobot
class IntentClassifier:
    """
    Mengklasifikasikan intent user menggunakan weighted keyword matching.
    Frasa panjang mendapat bobot lebih tinggi (lebih spesifik).
    """

    def __init__(self):
        self.intent_keywords: Dict[str, List[Tuple[str, int]]] = {
            "salam": [
                ("halo", 2), ("hai", 2), ("hi", 2), ("hello", 2),
                ("selamat pagi", 3), ("selamat siang", 3),
                ("selamat sore", 3), ("selamat malam", 3),
                ("assalamualaikum", 3), ("permisi", 1), ("hei", 1),
            ],
            "terima_kasih": [
                ("terima kasih", 3), ("thanks", 2), ("makasih", 2),
                ("thank you", 3), ("thx", 2), ("tq", 2), ("trims", 2),
            ],
            "bantuan": [
                ("bantuan", 2), ("help", 2), ("tolong bantu", 3),
                ("apa yang bisa kamu lakukan", 4), ("fitur", 2),
                ("panduan", 2), ("apa saja yang bisa", 3), ("command", 2),
            ],
            "definisi_stunting": [
                ("apa itu stunting", 5), ("stunting adalah", 4),
                ("definisi stunting", 5), ("pengertian stunting", 5),
                ("stunting itu apa", 5), ("arti stunting", 4),
                ("jelaskan stunting", 4), ("apa stunting", 3), ("stunting", 1),
            ],
            "penyebab_stunting": [
                ("penyebab stunting", 5), ("kenapa anak stunting", 5),
                ("faktor stunting", 4), ("faktor risiko stunting", 5),
                ("sebab stunting", 4), ("apa yang menyebabkan stunting", 5),
                ("mengapa stunting", 4), ("apa penyebab stunting", 5),
                ("penyebab", 1),
            ],
            "pencegahan_stunting": [
                ("mencegah stunting", 5), ("cegah stunting", 5),
                ("cara pencegahan stunting", 5),
                ("bagaimana mencegah stunting", 5),
                ("pencegahan stunting", 5), ("tips stunting", 3),
                ("cara mengatasi stunting", 4),
                ("mencegah", 1), ("pencegahan", 1),
            ],
            "ciri_stunting": [
                ("ciri stunting", 5), ("tanda stunting", 5),
                ("gejala stunting", 5), ("ciri ciri stunting", 5),
                ("tanda tanda stunting", 5),
                ("anak stunting seperti apa", 4),
                ("bagaimana ciri anak stunting", 5),
                ("ciri", 1), ("tanda", 1), ("gejala", 1),
            ],
            "makanan_stunting": [
                ("makanan untuk stunting", 5), ("makanan cegah stunting", 5),
                ("makanan anak stunting", 5), ("gizi stunting", 4),
                ("makanan bergizi anak", 4), ("nutrisi stunting", 4),
                ("menu stunting", 4), ("saran gizi", 3),
                ("asupan stunting", 4), ("makanan baik untuk anak", 4),
                ("makanan", 1), ("gizi", 1), ("nutrisi", 1),
            ],
            "dampak_stunting": [
                ("dampak stunting", 5), ("akibat stunting", 5),
                ("efek stunting", 4), ("bahaya stunting", 4),
                ("dampak jangka panjang stunting", 5),
                ("risiko stunting", 4),
                ("dampak", 1), ("akibat", 1), ("bahaya", 1),
            ],
            "peran_orang_tua": [
                ("peran orang tua", 5), ("peran keluarga stunting", 5),
                ("apa yang harus dilakukan orang tua", 5),
                ("orang tua bisa apa", 4), ("peran ibu stunting", 4),
                ("tips orang tua stunting", 4), ("orang tua", 2),
            ],
        }
        self.CONFIDENCE_THRESHOLD = 2

    def classify(self, text: str, context=None) -> Tuple[str, float]:
        phrases_set = set(SimpleNLP.get_all_phrases(text))
        normalized  = SimpleNLP.normalize(text)
        intent_scores: Dict[str, float] = {}
        for intent, keywords in self.intent_keywords.items():
            score = 0.0
            for keyword, weight in keywords:
                if keyword in phrases_set or keyword in normalized:
                    score += weight
            if score > 0:
                intent_scores[intent] = score
        if not intent_scores:
            if context and context.last_intent:
                resolved = self._resolve_with_context(text, context.last_intent)
                if resolved:
                    return resolved, 0.3
            return "unknown", 0.0
        best_intent = max(intent_scores, key=lambda k: intent_scores[k])
        best_score  = intent_scores[best_intent]
        if best_score < self.CONFIDENCE_THRESHOLD:
            if context and context.last_intent:
                resolved = self._resolve_with_context(text, context.last_intent)
                if resolved:
                    return resolved, 0.3
            return "unknown", 0.0
        return best_intent, min(best_score / 10.0, 1.0)

    def _resolve_with_context(self, text: str, last_intent: str) -> Optional[str]:
        """Disambiguasi dengan intent sebelumnya (context chaining)."""
        follow_up_words = {"kenapa", "mengapa", "lanjut", "terus",
                           "selanjutnya", "lebih", "dan"}
        tokens = set(SimpleNLP.tokenize(text))
        if tokens & follow_up_words:
            follow_up_map = {
                "definisi_stunting":   "penyebab_stunting",
                "penyebab_stunting":   "pencegahan_stunting",
                "pencegahan_stunting": "makanan_stunting",
                "ciri_stunting":       "dampak_stunting",
            }
            return follow_up_map.get(last_intent)
        return None

#RESPONSE GENERATOR - Template Jawaban Per Intent
class ResponseGenerator:
    """Menghasilkan respons informatif berdasarkan intent."""

    def __init__(self):
        self.responses: Dict[str, str] = {

            "salam": (
                "Halo! Saya NutriScan Bot, asisten edukasi stunting Anda.\n\n"
                "Yang bisa saya bantu:\n"
                "- Informasi lengkap tentang stunting\n"
                "- Penyebab dan faktor risiko stunting\n"
                "- Cara pencegahan stunting\n"
                "- Ciri-ciri anak stunting\n"
                "- Rekomendasi makanan bergizi\n"
                "- Dampak stunting jangka panjang\n"
                "- Peran orang tua dalam mencegah stunting\n\n"
                "Ada yang ingin ditanyakan?"
            ),

            "terima_kasih": (
                "Sama-sama! Senang bisa membantu Anda.\n\n"
                "Jangan ragu bertanya lagi jika ada yang ingin diketahui "
                "seputar stunting. Kesehatan anak adalah prioritas utama!"
            ),

            "bantuan": (
                "Panduan NutriScan Bot:\n\n"
                "1. 'Apa itu stunting?' - Pengertian stunting\n"
                "2. 'Kenapa anak bisa stunting?' - Penyebab stunting\n"
                "3. 'Bagaimana mencegah stunting?' - Tips pencegahan\n"
                "4. 'Bagaimana ciri anak stunting?' - Tanda-tanda stunting\n"
                "5. 'Makanan apa yang baik untuk cegah stunting?' - Gizi anak\n"
                "6. 'Apa dampak stunting jangka panjang?' - Dampak stunting\n"
                "7. 'Apa yang bisa dilakukan orang tua?' - Peran keluarga\n\n"
                "Gunakan juga fitur deteksi stunting di form input data anak!"
            ),

            "definisi_stunting": (
                "APA ITU STUNTING?\n\n"
                "Stunting adalah kondisi gagal tumbuh pada anak balita (0-59 bulan) "
                "akibat kekurangan gizi kronis, terutama selama 1000 Hari Pertama "
                "Kehidupan (HPK) - sejak dalam kandungan hingga usia 2 tahun.\n\n"
                "Indikator WHO:\n"
                "Anak dinyatakan stunting jika tinggi badan menurut usia (TB/U) "
                "berada di bawah -2 SD dari standar pertumbuhan WHO.\n\n"
                "Fakta Indonesia:\n"
                "Stunting bukan hanya masalah tinggi badan pendek, tetapi juga "
                "berdampak pada kecerdasan, produktivitas, dan kualitas hidup "
                "anak di masa depan.\n\n"
                "Tanyakan juga: 'Penyebab stunting?' atau 'Cara mencegah stunting?'"
            ),

            "penyebab_stunting": (
                "PENYEBAB STUNTING:\n\n"
                "Faktor Gizi:\n"
                "- Kekurangan asupan protein, zat besi, zinc, dan vitamin A\n"
                "- ASI tidak diberikan eksklusif selama 6 bulan\n"
                "- MPASI tidak bergizi, tidak tepat waktu, dan tidak higienis\n\n"
                "Faktor Kesehatan:\n"
                "- Infeksi berulang: diare, ISPA, cacingan\n"
                "- Kurang imunisasi dasar\n"
                "- Berat badan lahir rendah (BBLR)\n\n"
                "Faktor Lingkungan & Sosial:\n"
                "- Sanitasi buruk dan akses air bersih terbatas\n"
                "- Kemiskinan dan ketahanan pangan rendah\n"
                "- Pendidikan ibu yang rendah\n"
                "- Jarak kelahiran anak yang terlalu dekat\n\n"
                "Pelajari cara mencegah stunting untuk melindungi anak Anda!"
            ),

            "pencegahan_stunting": (
                "CARA MENCEGAH STUNTING:\n\n"
                "Untuk Bayi (0-6 bulan):\n"
                "- ASI eksklusif tanpa tambahan makanan/minuman lain\n"
                "- Pastikan ibu mendapat gizi cukup saat menyusui\n\n"
                "Untuk Balita (6-59 bulan):\n"
                "- MPASI bergizi: protein hewani, sayur, buah, karbohidrat\n"
                "- Variasi menu sesuai usia dan tekstur yang tepat\n"
                "- Makan minimal 3-5 kali sehari\n\n"
                "Pemantauan Kesehatan:\n"
                "- Timbang dan ukur tinggi badan setiap bulan di posyandu\n"
                "- Lengkapi imunisasi dasar\n"
                "- Berikan vitamin A setiap 6 bulan\n\n"
                "Lingkungan:\n"
                "- Cuci tangan sebelum makan dan setelah BAB\n"
                "- Gunakan jamban sehat dan air minum bersih"
            ),

            "ciri_stunting": (
                "CIRI-CIRI ANAK STUNTING:\n\n"
                "Pertumbuhan Fisik:\n"
                "- Tinggi badan di bawah rata-rata anak seusianya\n"
                "- Berat badan sering tidak naik beberapa bulan berturut-turut\n"
                "- Wajah tampak lebih muda dari usia sebenarnya\n\n"
                "Perkembangan:\n"
                "- Keterlambatan motorik: telat duduk, berdiri, berjalan\n"
                "- Perkembangan kognitif dan bicara lebih lambat\n"
                "- Kurang aktif dan mudah lelah\n\n"
                "Kesehatan:\n"
                "- Mudah sakit dan rentan terhadap infeksi\n"
                "- Nafsu makan sering buruk\n"
                "- Daya tahan tubuh rendah\n\n"
                "PENTING: Diagnosis resmi harus dilakukan tenaga kesehatan "
                "dengan mengukur TB/U dan membandingkan standar WHO. "
                "Segera periksakan ke posyandu atau puskesmas!"
            ),

            "makanan_stunting": (
                "MAKANAN BERGIZI UNTUK CEGAH & ATASI STUNTING:\n\n"
                "Protein Hewani (WAJIB setiap hari):\n"
                "- Telur: protein & kolin terbaik, min. 1 butir/hari\n"
                "- Ikan (teri, kembung, salmon): omega-3 & protein tinggi\n"
                "- Ayam & hati ayam: protein & zat besi\n"
                "- Susu & keju: kalsium & vitamin D\n"
                "- Tempe & tahu: protein nabati terjangkau\n\n"
                "Karbohidrat: nasi, ubi jalar, jagung, kentang\n\n"
                "Sayuran & Buah:\n"
                "- Bayam, brokoli, wortel: zat besi & vitamin A\n"
                "- Pepaya, pisang, mangga: vitamin C\n\n"
                "Lemak Sehat: minyak ikan, alpukat, kacang-kacangan\n\n"
                "Tips: Variasikan warna di piring anak setiap makan. "
                "Sesuaikan tekstur dengan usia: lumat (6 bln), cincang (9 bln), "
                "makanan keluarga (12 bln+)."
            ),

            "dampak_stunting": (
                "DAMPAK STUNTING JANGKA PANJANG:\n\n"
                "Kognitif & Pendidikan:\n"
                "- Kemampuan belajar dan konsentrasi menurun\n"
                "- Prestasi akademik rata-rata lebih rendah\n"
                "- Risiko putus sekolah lebih tinggi\n\n"
                "Fisik & Produktivitas:\n"
                "- Postur tubuh pendek saat dewasa\n"
                "- Kapasitas kerja fisik berkurang\n"
                "- Pendapatan rata-rata lebih rendah saat dewasa\n\n"
                "Kesehatan Dewasa:\n"
                "- Risiko penyakit tidak menular: diabetes, hipertensi, jantung\n"
                "- Sistem imun lemah sepanjang hidup\n\n"
                "Dampak Lintas Generasi:\n"
                "- Perempuan stunting berisiko melahirkan bayi BBLR\n"
                "- Siklus stunting dapat berlanjut ke generasi berikutnya\n\n"
                "Kesimpulan: Mencegah stunting = investasi masa depan anak & bangsa!"
            ),

            "peran_orang_tua": (
                "PERAN ORANG TUA DALAM MENCEGAH STUNTING:\n\n"
                "Sejak Kehamilan:\n"
                "- Konsumsi tablet tambah darah dan asam folat\n"
                "- Periksa kehamilan (ANC) minimal 4 kali\n"
                "- Hindari rokok dan asap rokok\n\n"
                "Masa Bayi (0-2 tahun):\n"
                "- Berikan ASI eksklusif 6 bulan, lanjutkan hingga 2 tahun\n"
                "- Mulai MPASI bergizi sejak usia 6 bulan\n"
                "- Pantau tumbuh kembang rutin ke posyandu\n\n"
                "Edukasi Diri:\n"
                "- Pelajari gizi anak dan cara penyajian makanan yang tepat\n"
                "- Ikuti kelas parenting atau penyuluhan gizi\n\n"
                "Lingkungan Rumah:\n"
                "- Pastikan sanitasi layak dan air bersih tersedia\n"
                "- Biasakan cuci tangan pakai sabun\n\n"
                "Stimulasi Tumbuh Kembang:\n"
                "- Ajak bicara, bermain, dan membaca buku sejak bayi\n\n"
                "Tumbuh kembang optimal adalah hak setiap anak!"
            ),

            "unknown": (
                "Maaf, saya belum memahami pertanyaan Anda.\n\n"
                "Silakan tanyakan seputar:\n"
                "- 'Apa itu stunting?'\n"
                "- 'Kenapa anak bisa stunting?'\n"
                "- 'Bagaimana mencegah stunting?'\n"
                "- 'Bagaimana ciri anak stunting?'\n"
                "- 'Makanan apa yang baik untuk cegah stunting?'\n"
                "- 'Apa dampak stunting jangka panjang?'\n"
                "- 'Apa yang bisa dilakukan orang tua?'\n\n"
                "Atau ketik 'bantuan' untuk panduan lengkap."
            ),
        }

    def generate(self, intent: str) -> str:
        return self.responses.get(intent, self.responses["unknown"])

#MAIN CHATBOT CLASS
class StuntingChatbot:
    """
    Chatbot edukasi stunting lengkap dengan NLP sederhana + context handling.

    Fitur:
    - Intent classification (weighted keyword matching + n-gram)
    - Tokenisasi & normalisasi berbasis regex
    - Context handling (history chat 5 giliran terakhir)
    - Response generation terstruktur dan informatif
    - Siap diintegrasikan ke FastAPI endpoint /chat
    """

    def __init__(self):
        self.nlp        = SimpleNLP()
        self.classifier = IntentClassifier()
        self.generator  = ResponseGenerator()
        self.context    = ChatContext(max_history=5)
        print("StuntingChatbot berhasil diinisialisasi!")

    def get_response(self, message: str) -> Dict:
        """
        Proses pesan user dan kembalikan respons.

        Args:
            message (str): Pesan dari user

        Returns:
            dict: {
                'response'   : str   - teks jawaban bot,
                'intent'     : str   - intent yang terdeteksi,
                'confidence' : float - tingkat keyakinan (0.0-1.0)
            }
        """
        if not message or not message.strip():
            return {
                "response": "Mohon ketikkan pertanyaan Anda.",
                "intent": "empty",
                "confidence": 0.0
            }
        normalized = self.nlp.normalize(message)
        intent, confidence = self.classifier.classify(normalized, self.context)
        response_text = self.generator.generate(intent)
        self.context.add_message("user", message, intent)
        self.context.add_message("bot",  response_text)
        return {
            "response":   response_text,
            "intent":     intent,
            "confidence": round(confidence, 2)
        }

    def reset_context(self):
        self.context.reset()
        print("Context percakapan telah direset.")

    def get_history(self) -> List[Dict]:
        return self.context.get_history()

# Inisialisasi global (dipakai FastAPI)
chatbot = StuntingChatbot()
print("Chatbot siap digunakan!")

#UNIT TEST - Cek semua intent sesuai FAQ penugasan
TEST_CASES = [
    ("Halo!",                                          "salam"),
    ("Selamat pagi",                                   "salam"),
    ("Apa itu stunting?",                              "definisi_stunting"),
    ("Tolong jelaskan stunting",                       "definisi_stunting"),
    ("Kenapa anak bisa stunting?",                     "penyebab_stunting"),
    ("Apa penyebab stunting?",                         "penyebab_stunting"),
    ("Bagaimana mencegah stunting?",                   "pencegahan_stunting"),
    ("Cara cegah stunting",                            "pencegahan_stunting"),
    ("Bagaimana ciri anak stunting?",                  "ciri_stunting"),
    ("Tanda-tanda stunting apa saja?",                 "ciri_stunting"),
    ("Makanan apa yang baik untuk cegah stunting?",    "makanan_stunting"),
    ("Saran gizi untuk anak stunting",                 "makanan_stunting"),
    ("Apa dampak stunting jangka panjang?",            "dampak_stunting"),
    ("Bahaya stunting itu apa?",                       "dampak_stunting"),
    ("Apa yang bisa dilakukan orang tua?",             "peran_orang_tua"),
    ("Peran keluarga dalam mencegah stunting",         "peran_orang_tua"),
    ("Terima kasih",                                   "terima_kasih"),
    ("Bantuan",                                        "bantuan"),
    ("Blablabla tidak jelas",                          "unknown"),
]

bot_test = StuntingChatbot()
PASS, FAIL = 0, 0

print("=" * 65)
print(f"{'PESAN USER':<40} {'EXPECTED':<22} {'RESULT'}")
print("=" * 65)

for msg, expected_intent in TEST_CASES:
    result = bot_test.get_response(msg)
    actual = result["intent"]
    ok = actual == expected_intent
    status = "PASS" if ok else "FAIL"
    if ok: PASS += 1
    else:  FAIL += 1
    print(f"{msg[:38]:<40} {expected_intent:<22} {status}")

print("=" * 65)
print(f"Hasil: {PASS}/{len(TEST_CASES)} test lulus | {FAIL} gagal")
if FAIL == 0:
    print("Semua test LULUS! Chatbot engine siap digunakan.")
else:
    print(f"{FAIL} test gagal. Periksa kembali keyword mapping.")

#DEMO - Simulasi percakapan lengkap (sesuai FAQ penugasan)
bot_demo = StuntingChatbot()

PERCAKAPAN = [
    "Halo!",
    "Apa itu stunting?",
    "Kenapa anak bisa stunting?",
    "Bagaimana cara mencegah stunting?",
    "Bagaimana ciri anak stunting?",
    "Makanan apa yang baik untuk cegah stunting?",
    "Apa dampak stunting jangka panjang?",
    "Apa yang bisa dilakukan orang tua?",
    "Terima kasih",
]

print("=" * 60)
print("  DEMO PERCAKAPAN NUTRISCAN BOT")
print("=" * 60)

for msg in PERCAKAPAN:
    result = bot_demo.get_response(msg)
    print(f"\nUser  : {msg}")
    print(f"Intent: {result['intent']}  (conf: {result['confidence']})")
    # Tampilkan 3 baris pertama respons
    lines = result['response'].split('\n')[:3]
    for i, line in enumerate(lines):
        prefix = 'Bot   : ' if i == 0 else '        '
        print(f"{prefix}{line}")
    if len(result['response'].split('\n')) > 3:
        print("        [... lihat respons lengkap di atas]")

print("\n" + "=" * 60)
print(f"Total pesan dalam history: {len(bot_demo.get_history())}")

#DEMO CONTEXT HANDLING
#Bot mengingat topik sebelumnya untuk menjawab follow-up
bot_ctx = StuntingChatbot()

context_convo = [
    ("Halo",             "Sapaan - bot menyambut"),
    ("Apa itu stunting?","Tanya definisi"),
    ("Kenapa?",          "Follow-up ambigu - bot gunakan context"),
    ("Lanjut dong",      "Follow-up lanjutan - context chaining"),
]

print("=" * 60)
print("  DEMO CONTEXT HANDLING")
print("=" * 60)

for msg, keterangan in context_convo:
    result = bot_ctx.get_response(msg)
    print(f"\n[{keterangan}]")
    print(f"User   : {msg}")
    print(f"Intent : {result['intent']}  (conf: {result['confidence']})")
    print(f"Bot    : {result['response'].split(chr(10))[0]}")

print("\n" + "=" * 60)
print("History Chat:")
for h in bot_ctx.get_history():
    ts = h.get('timestamp', '')
    print(f"  [{ts}] {h['role'].upper():<5}: {h['message'][:55]}")