# -*- coding: utf-8 -*-
"""data pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qGysRkIBfjIopYL-0Z11PBvZowfoDLVQ
"""

import yaml
from pathlib import Path

# Configuration Pipeline Data Stunting in YAML format
config_content = """
data_sources:
  raw_data_path: "data/raw/stunting_raw.csv"
  backup_path: "data/backup/"

output:
  clean_csv_path: "data/clean/stunting_clean.csv"
  rejected_csv_path: "data/quarantine/stunting_rejected.csv"
  db_path: "data/database/stunting.db"
  db_table: "stunting_clean"

preprocessing:
  # Batasan nilai valid (berdasarkan standar kesehatan)
  usia_bulan_min: 0
  usia_bulan_max: 60        # anak 0-5 tahun
  tinggi_cm_min: 40
  tinggi_cm_max: 120
  berat_kg_min: 2.0
  berat_kg_max: 30.0

  # Kolom yang wajib ada
  required_columns:
    - "id_anak"
    - "usia_bulan"
    - "jenis_kelamin"
    - "tinggi_cm"
    - "berat_kg"
    - "tanggal_ukur"

logging:
  level: "INFO"
  log_file: "logs/pipeline.log"
"""

# Define the path for the config file
config_path = "config.yaml"

# Ensure the directory for the config file exists
Path(config_path).parent.mkdir(parents=True, exist_ok=True)

# Write the YAML content to the config.yaml file
with open(config_path, "w") as f:
    f.write(config_content)

print(f"Configuration saved to {config_path}")

from google.colab import files
import pandas as pd
import os

print("upload file CSV data stunting (yang kacau)")
uploaded = files.upload()

# Ambil nama file yang baru saja diupload
for filename in uploaded.keys():
    print(f"File {filename} berhasil diupload")
    # Rename ke stunting_raw.csv agar pipeline bisa membaca
    os.rename(f"/content/{filename}", "/content/stunting_raw.csv")
    print(f"File diubah namanya menjadi stunting_raw.csv")
    break

# Verifikasi
!ls -la /content/*.csv

# ===============================
# DATA PIPELINE - Klasifikasi Stunting
# ===============================

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import joblib

# 1. Load dataset (sudah clean)
df = pd.read_csv('stunting_raw.csv')

# 2. Pisahkan fitur (X) dan target (y)
X = df.drop('Stunting', axis=1)
y = df['Stunting']

# 3. Definisikan kolom berdasarkan tipe
numeric_features = ['Age', 'Height', 'Weight', 'BMI']
categorical_features = ['Age_Group']

# 4. Buat preprocessor
numeric_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(drop='first', handle_unknown='ignore')

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# 5. Bangun pipeline lengkap dengan classifier (Random Forest)
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42, n_jobs=-1))
])

# 6. Bagi data training dan testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 7. Latih pipeline pada data training
pipeline.fit(X_train, y_train)

# 8. Evaluasi dasar
y_pred = pipeline.predict(X_test)

print("=== HASIL EVALUASI MODEL ===")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Check if the model has learned more than one class to compute ROC-AUC
if len(pipeline.classes_) > 1:
    y_proba = pipeline.predict_proba(X_test)[:, 1]
    print("ROC-AUC Score:", roc_auc_score(y_test, y_proba))
else:
    print("Warning: The target variable 'Stunting' contains only one unique class (all 0s).")
    print("ROC-AUC score cannot be calculated for a single-class dataset.")
    y_proba = None # Set to None as it's not meaningful in this context.

# 9. Cross-validation (opsional)
# This will also likely be problematic if only one class is present in y.
if len(pipeline.classes_) > 1:
    cv_scores = cross_val_score(pipeline, X, y, cv=5, scoring='roc_auc')
    print(f"Cross-validated ROC-AUC: {cv_scores.mean():.3f} (+/- {cv_scores.std():.3f})")
else:
    print("Warning: Only one class found in target variable. Cross-validated ROC-AUC is not applicable.")

# 10. Hyperparameter tuning (pencarian parameter terbaik)
# GridSearchCV with scoring='roc_auc' will also face issues if y contains only one class.
param_grid = {
    'classifier__n_estimators': [50, 100, 200],
    'classifier__max_depth': [None, 10, 20],
    'classifier__min_samples_split': [2, 5]
}

# It's recommended to address the dataset's single-class issue for GridSearchCV's roc_auc scoring.
if len(pipeline.classes_) > 1:
    grid_search = GridSearchCV(pipeline, param_grid, cv=3, scoring='roc_auc', n_jobs=-1, verbose=1)
    grid_search.fit(X_train, y_train)

    print("\n=== HASIL TUNING ===")
    print("Best parameters:", grid_search.best_params_)
    print("Best ROC-AUC (CV):", grid_search.best_score_)
else:
    print("\n=== HYPERPARAMETER TUNING SKIPPED ===")
    print("Warning: Hyperparameter tuning with 'roc_auc' scoring skipped because target variable 'Stunting' contains only one unique class.")
    print("Please provide a dataset with at least two classes for meaningful tuning.")